# == Schema Information
#
# Table name: media
#
#  created_at            :datetime         not null
#  id                    :integer          not null, primary key
#  item                  :string
#  item_content_type     :string
#  item_file_size        :integer
#  item_height           :integer
#  item_width            :integer
#  kind_value            :string
#  media_attachable_id   :integer
#  media_attachable_type :string
#  sort_order            :integer
#  updated_at            :datetime         not null
#  uploader_id           :integer
#
# Indexes
#
#  index_media_on_media_attachable_type_and_media_attachable_id  (media_attachable_type,media_attachable_id)
#
# Foreign Keys
#
#  fk_rails_d64ff8d67d  (uploader_id => people.id)
#

class Media < ActiveRecord::Base
  include Translatable
  include OptionSettable

  belongs_to :media_attachable, polymorphic: true
  belongs_to :uploader, class_name: 'Person'

  mount_uploader :item, MediaItemUploader
  validates :item, :kind_value, presence: true
  attr_translatable :caption, :description

  delegate :division, :division=, to: :media_attachable

  scope :images_only, -> { where(kind_value: 'image') }

  # Beware, the methods generated by this include will fail
  # without the corresponding OptionSet records existing in the database.
  attr_option_settable :kind

  after_commit :recalculate_loan

  def alt
    self.try(:caption) || self.media_attachable.try(:name)
  end

  def thumbnail?
    kind_value == 'image'
  end

  def recalculate_loan
    # Only submit a job if it is a Loan
    RecalculateLoanJob.perform_later(loan_id: media_attachable_id) if media_attachable_type == 'Project'
  end
end
